name: Github Issues Actions
on:
  issues:
    types: [opened, edited]

jobs:
  list_issues_information:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue information
        run: echo "The issue title is ${{ github.event.issue.title }} and the body is ${{ github.event.issue.body }}"
      - name: Get all issue information
        run: echo "All issue data ${{github.event.issue}}"
