name: Output github information
on: workflow_dispatch
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "The repository is ${{ github.repository }}"
      - name: Output event name
        run: echo "The event name is ${{ github.event_name }}"
      - name: Output the current branch
        run: echo "The current branch is ${{ github.ref }}"
      - name: Output github in general
        run: echo "The github context is ${{ toJson(github) }}"
